export const BRANDS = {
  AUTO: [
    "Audi",
    "BMW",
    "Mercedes-Benz",
    "Volkswagen",
    "Porsche",
    "Opel",
    "Ford",
    "Renault",
    "Peugeot",
    "Citroën",
    "Fiat",
    "Toyota",
    "Honda",
    "Nissan",
    "Mazda",
    "Hyundai",
    "Kia",
    "Volvo",
    "SEAT",
    "Škoda",
    "Alfa Romeo",
    "Jaguar",
    "Land Rover",
    "Mini",
    "Smart",
    "Subaru",
    "Suzuki",
    "Mitsubishi",
    "Lexus",
    "Infiniti",
    "Acura",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Dodge",
    "Jeep",
    "Lincoln",
    "Buick",
    "GMC",
    "Tesla",
    "Lucid",
    "Rivian",
  ],
  MOTO: [
    "BMW",
    "Honda",
    "Yamaha",
    "Kawasaki",
    "Suzuki",
    "Ducati",
    "Harley-Davidson",
    "KTM",
    "Aprilia",
    "Triumph",
    "Moto Guzzi",
    "Indian",
    "Can-Am",
    "Polaris",
    "Zero",
    "Energica",
    "Lightning",
    "Husqvarna",
    "Beta",
    "Gas Gas",
    "Sherco",
    "TM Racing",
    "Husaberg",
    "Montesa",
    "Scorpa",
    "Ossa",
    "Rieju",
    "Derbi",
  ],
}

export const FUEL_TYPES = ["Benzyna", "Diesel", "Hybryda", "Elektryczny", "LPG", "CNG", "Wodór"]

export const TRANSMISSION_TYPES = ["Manualna", "Automatyczna", "Półautomatyczna", "CVT"]

export const SWISS_CITIES = [
  "Zürich",
  "Genève",
  "Basel",
  "Bern",
  "Lausanne",
  "Winterthur",
  "Luzern",
  "St. Gallen",
  "Lugano",
  "Biel/Bienne",
  "Thun",
  "Köniz",
  "La Chaux-de-Fonds",
  "Schaffhausen",
  "Fribourg",
  "Chur",
  "Neuchâtel",
  "Uster",
  "Sion",
  "Emmen",
  "Zug",
  "Yverdon-les-Bains",
  "Dübendorf",
  "Dietikon",
  "Montreux",
  "Frauenfeld",
  "Wetzikon",
  "Aarau",
  "Baden",
  "Bellinzona",
]

export const VEHICLE_CONDITIONS = ["Nowy", "Używany", "Uszkodzony", "Do remontu", "Zabytkowy"]

export const BODY_TYPES = {
  AUTO: [
    "Sedan",
    "Hatchback",
    "Kombi",
    "SUV",
    "Coupe",
    "Cabrio",
    "Minivan",
    "Pickup",
    "Crossover",
    "Limuzyna",
    "Roadster",
    "Targa",
  ],
  MOTO: [
    "Naked",
    "Sport",
    "Touring",
    "Cruiser",
    "Adventure",
    "Enduro",
    "Cross",
    "Scooter",
    "Chopper",
    "Cafe Racer",
    "Bobber",
    "Trike",
  ],
}

export const DRIVE_TYPES = ["Przedni", "Tylni", "4x4", "AWD"]

export const COLORS = [
  "Biały",
  "Czarny",
  "Srebrny",
  "Szary",
  "Czerwony",
  "Niebieski",
  "Zielony",
  "Żółty",
  "Pomarańczowy",
  "Brązowy",
  "Fioletowy",
  "Różowy",
  "Złoty",
  "Beżowy",
]
